events {}


http {
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    upstream backend {
        server booking_back:8000;
    }

    server {
        listen 80;

        location / {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }

        location /docs {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /nginx-status {
            stub_status;
            allow 127.0.0.1;
            allow 172.0.0.0/8;
            deny all;
        }
    }
}